import { api } from 'finnaz/utils/api'
import { type NextPage } from 'next'
import { toast } from 'react-hot-toast'
import Head from 'next/head'
import React, { useState } from 'react'
const Home: NextPage = () => {
	const getDate = () => {
		const currentDate = new Date()
		const hours = currentDate.getHours()
		const minutes = currentDate.getMinutes()
		const seconds = currentDate.getSeconds()
		const date = currentDate.toISOString()
		return {
			time: `${hours.toString().padStart(2, '0')}:${minutes
				.toString()
				.padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`,
			date,
		}
	}
	const [amount, setAmount] = useState<number>(0)
	const ctx = api.useContext()
	const { mutate, isLoading: isPosting } = api.purchases.create.useMutation({
		onSuccess: () => {
			void ctx.purchases.getAll.invalidate()
		},
		onError: e => {
			const errorMessage = e.data?.zodError?.fieldErrors.content
			if (errorMessage && errorMessage[0]) {
				toast.error(errorMessage[0])
			} else {
				toast.error('Failed to post! Please try again later.')
			}
		},
	})
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
				<form className="wrap flex h-4/5 w-1/3 flex-col items-center justify-center gap-8 rounded-xl border bg-[#00000033] p-4 backdrop-blur-lg">
					<input
						type="amount"
						value={amount}
						className="w-full border-b bg-transparent p-4 text-center align-middle text-white"
						onChange={e => {
							setAmount(parseInt(e.target.value))
						}}
					/>
					<button
						onClick={e => {
							e.preventDefault()
							const { time, date } = getDate()
							if (amount < 1000)
								alert(
									'Amount should be higher than $1,000.00 COP',
								)
							const result = mutate({
								date: date,
								amount: amount,
								time: time,
								userId: Math.floor(Math.random() * 100),
							})
							setAmount(0)
							console.log(result)
						}}
						className="w-fit rounded-lg bg-blue-200 p-2"
					>
						Add
					</button>
				</form>
			</main>
		</>
	)
}

export default Home
