import { api } from 'finnaz/utils/api'
import { type NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
const Home: NextPage = () => {
	function CreatePurchase() {
		const currentDate = new Date()
		const hours = currentDate.getHours()
		const minutes = currentDate.getMinutes()
		const seconds = currentDate.getSeconds()
		const Testing = api.purchases.addPurchase.useQuery({
			amount: 200000,
			date: currentDate.toISOString(),
			time: `${hours.toString().padStart(2, '0')}:${minutes
				.toString()
				.padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`,
			userId: 0,
		})
		return Testing
	}
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
				<div>
					<button
						onClick={e => {
							e.preventDefault()
							CreatePurchase()
						}}
						className="rounded-lg bg-blue-200 p-4 "
					>
						Add purchase
					</button>
				</div>
			</main>
		</>
	)
}

export default Home
